eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8002
spring:
  application:
    name: zuul
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
zuul:
  routes:
    manager:
      path: /manager/**
#      url: http://localhost:8004/
      service-id: manager
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 10000
